### ISSUE TITLE
Greenlet.py causing KeyError

### ISSUE THREAD

**Issue by thagoat** [andreimarcu/ttrss-irc#1]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/home/USER/ttrss-irc/plugins/ttrss.py", line 81, in onconnect
    self._login()
  File "/home/USER/ttrss-irc/plugins/ttrss.py", line 22, in _login
    self._sid = resp["content"]["session_id"]
KeyError: 'session_id'
2019-01-16T19:42:37Z <Greenlet at 0x7f94dce90890: <bound method TTRSS.onconnect of <plugins.ttrss.TTRSS object at 0x7f94dd30a610>>({'botnick': u'BOTNAME', u'triggers': <pyaib.trigg)> failed with KeyError
Got error running Python 2.7.15rc1 and Python 3.7.2

**Comment by Vincent18zt** [comment]
same error

**Comment by thagoat** [comment]
I went into settings and disabled the plug-in. Worked like a charm with no noticable difference in my feeds.

**Comment by andreimarcu** [comment]
Wow, did not realize anyone used this. 
Sadly I haven't used it in a while but I do remember at some point this was caused by the session expiring so I think you need to catch the exception and login whenever this happens.

I think I will archive the repo since I'm not working on it anymore, but if anyone wants to fork it I'll be happy to link to that
